version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_OPENAI_API_KEY=${REACT_APP_OPENAI_API_KEY}
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_OPENAI_API_KEY=${REACT_APP_OPENAI_API_KEY}
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
